
package g8.bookshop.business.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CatalogueServiceService", targetNamespace = "http://ws.business.bookshop.g8/", wsdlLocation = "http://localhost:8080/BookshopBusiness-BookshopBusinessCore/CatalogueService?wsdl")
public class CatalogueServiceService
    extends Service
{

    private final static URL CATALOGUESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(g8.bookshop.business.ws.CatalogueServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = g8.bookshop.business.ws.CatalogueServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/BookshopBusiness-BookshopBusinessCore/CatalogueService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/BookshopBusiness-BookshopBusinessCore/CatalogueService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CATALOGUESERVICESERVICE_WSDL_LOCATION = url;
    }

    public CatalogueServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogueServiceService() {
        super(CATALOGUESERVICESERVICE_WSDL_LOCATION, new QName("http://ws.business.bookshop.g8/", "CatalogueServiceService"));
    }

    /**
     * 
     * @return
     *     returns CatalogueService
     */
    @WebEndpoint(name = "CatalogueServicePort")
    public CatalogueService getCatalogueServicePort() {
        return super.getPort(new QName("http://ws.business.bookshop.g8/", "CatalogueServicePort"), CatalogueService.class);
    }

}
