
package g8.bookshop.business.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CatalogueService", targetNamespace = "http://ws.business.bookshop.g8/")
public interface CatalogueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FullSearch")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FullSearch", targetNamespace = "http://ws.business.bookshop.g8/", className = "g8.bookshop.business.ws.FullSearch")
    @ResponseWrapper(localName = "FullSearchResponse", targetNamespace = "http://ws.business.bookshop.g8/", className = "g8.bookshop.business.ws.FullSearchResponse")
    public String fullSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Search")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Search", targetNamespace = "http://ws.business.bookshop.g8/", className = "g8.bookshop.business.ws.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://ws.business.bookshop.g8/", className = "g8.bookshop.business.ws.SearchResponse")
    public String search(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
